spring:
  application:
    name: recipe
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #cloud:
    #azure:
     #servicebus:
      #namespace: saproneservicebus
      #entity-name: basket-queue
      #entity-type: queue
      #connection-string: ${SERVICE_BUS_CONNECTION_STRING}
server:
  port: 8084