name: Trigger auto deployment for recipegenerator-recipe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
      - '**'
      - '.github/workflows/recipegenerator-recipe-AutoDeployTrigger-13f13b68-5623-49c1-8adf-d3886860136a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' # Specify the Java version you need
          distribution: 'adopt'

      - name: Run unit tests with Maven
        run: mvn test

      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify sonar:sonar

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RECIPEGENERATORRECIPE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RECIPEGENERATORRECIPE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RECIPEGENERATORRECIPE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to Docker Hub
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.RECIPEGENERATORRECIPE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RECIPEGENERATORRECIPE_REGISTRY_PASSWORD }}
          containerAppName: recipegenerator-recipe
          resourceGroup: saprone-resource-group
          imageToBuild: saprone/recipegenerator-recipe:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


